version: '3.9'

services:
  # mysql:
  #   image: mysql:8
  #   ports:
  #     - 3306:3306
  #   volumes:
  #     - mysql_data:/var/lib/mysql
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=root
  #     - MYSQL_PASSWORD=root
  #     - MYSQL_USER=user
  #     - MYSQL_DATABASE=test
  #   networks:
  #     - app

  grow-reg:
    image: grow-reg:0.0.1
    command: tail -f /dev/null
    environment:
      - DB_USER=0hn96gileawlwr8zr0jx
      - DB_PASSWORD=pscale_pw_OEcV6RVECQggckOyELlCJyoxaofFPXLrnwORmnE5Bro
      - DB_HOST=aws.connect.psdb.cloud
      - DB_NAME=grow-reg
      - DB_CHARSET=utf8mb4
    ports:
      - 8080:8080
    networks:
      - app
    # depends_on:
    #   - mysql
    

networks:
  app:
    driver: bridge

volumes:
  mysql_data: